AllCops:
  Exclude:
    - db/migrate/*
    - db/schema.rb
    - config/**/*
    - script/**/*
    - vendor/bundle/**/*
    - bin/*
    - Gemfile*
    - node_modules/**/*

Layout/EmptyLinesAroundAttributeAccessor:
  Enabled: true

Layout/SpaceAroundMethodCallOperator:
  Enabled: true

Lint/RaiseException:
  Enabled: true

Lint/StructNewOverride:
  Enabled: true

Style/ExponentialNotation:
  Enabled: true

Style/HashEachMethods:
  Enabled: true

Style/HashTransformKeys:
  Enabled: true

Style/HashTransformValues:
  Enabled: true

Style/SlicingWithRange:
  Enabled: true

Layout/MultilineMethodCallBraceLayout:
  EnforcedStyle: new_line

Metrics/AbcSize:
  Max: 15

Metrics/CyclomaticComplexity:
  Max: 10

Layout/LineLength:
  Max: 120

Metrics/MethodLength:
  Max: 20

Naming/RescuedExceptionsVariableName:
  PreferredName: error

Style/Alias:
  EnforcedStyle: prefer_alias_method

Style/Documentation:
  Enabled: false

Style/FormatStringToken:
  EnforcedStyle: template

Style/NumericLiterals:
  Enabled: false

Style/RegexpLiteral:
  EnforcedStyle: slashes
  AllowInnerSlashes: true
