
language: ruby
cache: bundler
rvm:
  - 2.6.3
services:
  - postgresql
before_script:
  - RAILS_ENV=test bundle exec rake db:setup
script:
  - bundle exec rubocop
  - bundle exec reek
  - bundle exec rspec
